### ISSUE TITLE
CSS mixins for styling

### ISSUE THREAD

**Issue by chimon2000** [Collaborne/paper-bottom-sheet#4]
Need to be able to style paper-bottom-sheet-item using [CSS Mixins](https://www.polymer-project.org/1.0/docs/devguide/styling.html).

Suggested properties (taken from paper-button): 

--paper-bottom-sheet
--paper-bottom-sheet-item
--paper-bottom-sheet-item-color
--paper-bottom-sheet-item-ink-color 
--paper-bottom-sheet-item-disabled

**Comment by ronnyroeller** [comment]
Ryan, it's a good idea! Feel free to provide a PR, and I will merge it.
