### ISSUE TITLE
'disabled' paper-bottom-sheet-item still sends events such as on-tap

### ISSUE THREAD

**Issue by ankon** [Collaborne/paper-bottom-sheet#5]
```
<paper-bottom-sheet-item text="Foo" disabled on-tap="handleTapFoo"></paper-bottom-sheet-item>
```

I'd expect `handleTapFoo` not to be called on taps, as the component is disabled. Not sure whether that is a problem in the paper-bottom-sheet-item itself, or just something that needs to be handled more globally in polymer.

For now I'm working around this by checking the `disabled` state in `handleTapFoo`.

**Comment by srijken** [comment]
This may have been fixed by this issue: https://github.com/Polymer/polymer/issues/4685

Does this still happen?

**Comment by ankon** [comment]
I'm not sure really, I think I lost that code that needed it in a redesign. The issue you link to looks indeed related, so without further evidence of the problem I'll close this ticket. If needed it can be reopened :)

Thanks a lot for the reference!
