### ISSUE TITLE
Try to use paper-bottom-sheet in dom-repeat -> only opens one time

### ISSUE THREAD

**Issue by deaththeeny** [Collaborne/paper-bottom-sheet#8]
Hey Guys!

I want to use the paper-bottom-sheet for dynamic content, so my sheet is placed in a dom-repeat template. For one time it works, the sheet opens. I saw the issue #1 but I can't use dom-bind in my case.

I have this in my custom-element:

```
<dom-module id="xfe-training-event">
            <template is="dom-repeat" items="[[event]]">
                <section>
                    <paper-bottom-sheet class$="sheet[[item.index]]" slide>
                        [[item.map-link]]content
                    </paper-bottom-sheet>

                    <div class="map-link">
                        <iron-icon icon="my-icons:map"></iron-icon><span on-tap="openSheet" data-index$="[[item.index]]">Standort anzeigen</span>
                    </div>
                </section>
            </template>
    </template>

    <script>
        class XfeTrainingEvent extends Polymer.Element {

            openSheet(event) {
               this.shadowRoot.querySelector('.sheet' + event.target.dataset.index).open();
            }

           static get properties() {
                return {
                    event: {
                        type: Array
                    }
                }
            }

            static get is() { return 'xfe-training-event'; }
        }

        window.customElements.define(XfeTrainingEvent.is, XfeTrainingEvent);
    </script>
</dom-module>
```

Is it possible to open the sheet in this way more than one time?

Greets, Denise

**Comment by ronnyroeller** [comment]
The easiest solution is probably to move the `paper-bottom-sheet` and `iron-icon` into a separated element. Then you can use vanilla event binding to control the paper-button-sheet (instead of relying on `querySelector`):

```
<template>
  <paper-bottom-sheet id="sheet" slide>
    [[item.map-link]]content
  </paper-bottom-sheet>
  <div class="map-link">
    <iron-icon icon="my-icons:map"></iron-icon><span on-tap="openSheet">Standort anzeigen</span>
  </div>
</template>

<script>
class XfeTrainingEventEntry extends Polymer.Element {
  openSheet(event) {
    this.$.sheet.open();
  }
  ...
</script>
```

And use this element in your dom-repeat element:

```
<template is="dom-repeat" items="[[event]]">
  <xfe-training-event-entry event="[[event]]"></xfe-training-event-entry>
</template>
```

**Comment by derhuebiii** [comment]
Does this solve the problem that the paper-bottom-sheet is being removed all the time?

I have a similar issue. I have the paper-bottom-sheet inside another element. Calling once works fine, but through "appendChild" it gets moved to the document body and the removed on close.

Shouldn't just a "clone" be moved to document body? I tried to do with vanilla cloneNode function but it doesn't clone the slotted items properly :/

**Comment by derhuebiii** [comment]
@ronnyroeller 
I am totally puzzled now, I figured out it works only if I use the this.$.elementID, but not the querySelector:

Works once:

        Polymer.dom(this.root).querySelector('#bottomInteract').open(); //this does only work once, it removes the node then from document body and from the shadow dom


Works several times:

        this.$.bottomInteract.open(); //this works over and over

Any ideas?


EDIT: Seems like this.$. .... seems to cache the element somehow, because paper-bottom-sheet still gets removed within my element.
What I don't understand:
=> Why does appendChild in `.open()` remove the paper-bottom-sheet element?

Alternative solution:
=> Would it not be possible that just a "clone" is appended to the document.body?
